helmDefaults:
    wait: true
    atomic: true
    timeout: 600
    createNamespace: true

repositories:
    -   name: vector
        url: https://helm.vector.dev
    -   name: open-telemetry
        url: https://open-telemetry.github.io/opentelemetry-helm-charts
    -   name: traefik
        url: https://traefik.github.io/charts
    -   name: bitnami
        url: https://charts.bitnami.com/bitnami
    -   name: zitadel
        url: https://charts.zitadel.com
    -   name: openobserve
        url: https://charts.openobserve.ai

releases:
    -   name: prepare
        namespace: traefik-system
        chart: ./charts/prepare
        values:
            - charts/prepare/values.yaml
        labels:
            phase: prepare

    # ===== PHASE: operators (CRD providers + controllers) =====
    -   name: traefik
        namespace: traefik-system
        chart: traefik/traefik
        version: 37.0.0
        values:
            - values-traefik.yaml
        needs:
            - traefik-system/prepare
        labels:
            phase: operators

    # ===== PHASE: crd-objects (instances of CRDs) =====
    -   name: traefik-mw
        namespace: traefik-system
        chart: ./charts/traefik-mw
        needs:
            - traefik-system/traefik
        labels:
            phase: crd-objects

    # ===== PHASE: storage =====
    -   name: postgres
        namespace: zitadel
        chart: bitnami/postgresql
        version: 12.10.0
        values:
            - values-postgres.yaml
        labels:
            phase: storage

    # ===== PHASE: apps =====
    -   name: openobserve
        namespace: observability
        chart: openobserve/openobserve-standalone
        values:
            - values-openobserve.yaml
        needs:
            - traefik-system/traefik

    -   name: otelcol
        namespace: monitoring
        chart: open-telemetry/opentelemetry-collector
        values:
            - values-otelcol.yaml
        needs:
            - traefik-system/traefik
        labels:
            phase: apps

    -   name: zitadel
        namespace: zitadel
        chart: zitadel/zitadel
        version: 9.0.0
        values:
            - values-zitadel.yaml
        needs:
            - traefik-system/traefik
            - zitadel/postgres
        labels:
            phase: apps

    -   name: vector
        namespace: monitoring
        chart: vector/vector
        version: 0.45.0
        values:
            - values-vector.yaml
        needs:
            - traefik-system/traefik
            - monitoring/otelcol
        labels:
            phase: apps
