# values-otelcol.yaml — Collector -> OpenObserve via OTLP/HTTP

mode: deployment

image:
    repository: otel/opentelemetry-collector
    tag: "0.133.0"
    pullPolicy: IfNotPresent

service:
    type: ClusterIP

ports:
    otlp:
        enabled: true
        containerPort: 4317
        servicePort: 4317
    otlp-http:
        enabled: true
        containerPort: 4318
        servicePort: 4318
    metrics:
        enabled: true
        containerPort: 8888
        servicePort: 8888
    health:
        enabled: true
        containerPort: 13133
        servicePort: 13133
    jaeger-compact:
        enabled: false
    jaeger-thrift:
        enabled: false
    jaeger-grpc:
        enabled: false
    zipkin:
        enabled: false

config:
    receivers:
        jaeger: null
        zipkin: null
        prometheus: null
        otlp:
            protocols:
                grpc: {}        # REQUIRED: must be {} to enable
                http: {}

    processors:
        batch: {}

    exporters:
        debug:
            verbosity: basic
        otlphttp/o2:
            endpoint: "http://openobserve-openobserve-standalone.observability.svc.cluster.local:5080/api/default"
            headers:
                Authorization: "Basic YWRtaW5AZGV2Lm1yaWRhLm5nOkNoYW5nZU1lTm93IQ=="
                organization: "default"
                stream-name: "v1"

    extensions:
        health_check: {}    # REQUIRED: must be {} to exist

    service:
        extensions:
            - health_check
        telemetry:
            metrics:
                address: 0.0.0.0:8888
        pipelines:
            traces:
                receivers:
                    - otlp
                processors:
                    - batch
                exporters:
                    - debug
                    - otlphttp/o2
            metrics:
                receivers:
                    - otlp
                processors:
                    - batch
                exporters:
                    - debug
                    - otlphttp/o2
            logs:
                receivers:
                    - otlp
                processors:
                    - batch
                exporters:
                    - debug
                    - otlphttp/o2

serviceMonitor:
    enabled: false
