role: "Agent"

# Minimal security
securityContext:
    privileged: true

podSecurityContext:
    runAsUser: 0

# Use different volume name to avoid conflicts
extraVolumes:
    - name: host-var-log
      hostPath:
          path: /var/log
    - name: vector-data-dir
      emptyDir: {}

extraVolumeMounts:
    - name: host-var-log
      mountPath: /var/log
      readOnly: true
    - name: vector-data-dir
      mountPath: /var/lib/vector

# Clean environment
env:
    - name: VECTOR_LOG
      value: "debug"

# Disable service to avoid port issues
service:
    enabled: false

# Simple config with OpenObserve
customConfig:
    sources:
        kubernetes_logs:
            type: kubernetes_logs

        # NEW: host metrics (minimal)
        host_metrics:
            type: host_metrics

    sinks:
        # Keep console output for debugging
#        stdout:
#            type: console
#            inputs: ["kubernetes_logs"]
#            target: stdout
#            encoding:
#                codec: json

        # Send logs to OpenObserve (unchanged)
        oo_logs:
            type: http
            inputs: ["kubernetes_logs"]
            uri: "http://openobserve-openobserve-standalone.observability.svc.cluster.local:5080/api/default/default/_multi"
            method: post
            encoding:
                codec: json
            framing:
                method: newline_delimited
            request:
                headers:
                    Authorization: "Basic YWRtaW5AZGV2Lm1yaWRhLm5nOkNoYW5nZU1lTm93IQ=="
                    Content-Type: "application/json"
            compression: gzip
            buffer:
                type: memory
                max_events: 10000
                when_full: block
            healthcheck:
                enabled: true
                uri: "http://openobserve-openobserve-standalone.observability.svc.cluster.local:5080/healthz"

        # NEW: host metrics -> OpenObserve (Prometheus remote_write)
        oo_metrics:
            type: prometheus_remote_write
            inputs: ["host_metrics"]
            endpoint: "http://openobserve-openobserve-standalone.observability.svc.cluster.local:5080/api/default/prometheus/api/v1/write"
            auth:
                strategy: basic
                user: "admin@dev.mrida.ng"
                password: "ChangeMeNow!"
            healthcheck:
                enabled: false # https://github.com/vectordotdev/vector/issues/8279
